# Generated by Django 5.2.7 on 2025-10-22 10:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('full_name', models.CharField(help_text='Masalan: Ali Valiyev', max_length=120, verbose_name='To‘liq ism')),
                ('phone', models.CharField(help_text='Masalan: +998 90 123 45 67', max_length=32, validators=[django.core.validators.RegexValidator('^\\+?[0-9\\-\\s\\(\\)]{6,}$')], verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('preferred_contact', models.CharField(choices=[('phone', 'Telefon'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('email', 'Email')], default='phone', max_length=16, verbose_name='Aloqa usuli')),
                ('alt_destination', models.CharField(blank=True, help_text='Masalan: Turkiya, BAA... (tur tanlanmagan bo‘lsa).', max_length=150, verbose_name='Muqobil yo‘nalish')),
                ('desired_start_date', models.DateField(blank=True, null=True, verbose_name='Boshlanish sanasi')),
                ('days', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Necha kun')),
                ('adults', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Kattalar soni')),
                ('children', models.PositiveSmallIntegerField(default=0, verbose_name='Bolalar soni')),
                ('infants', models.PositiveSmallIntegerField(default=0, verbose_name='Chaqaloqlar soni')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Valyuta')),
                ('budget_from', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Byudjet dan')),
                ('budget_to', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Byudjet gacha')),
                ('message', models.TextField(blank=True, verbose_name='Izoh / talablar')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('in_review', 'Ko‘rib chiqilmoqda'), ('contacted', 'Aloqa qilindi'), ('won', 'Sotildi / band qilindi'), ('lost', 'Yo‘qotildi'), ('spam', 'Spam / nojo‘ya')], default='new', max_length=16, verbose_name='Holat')),
                ('utm_source', models.CharField(blank=True, max_length=64, verbose_name='UTM Source')),
                ('utm_medium', models.CharField(blank=True, max_length=64, verbose_name='UTM Medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=64, verbose_name='UTM Campaign')),
                ('referrer', models.CharField(blank=True, max_length=500, verbose_name='Referrer URL')),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Mijoz IP')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='User-Agent')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL, verbose_name='Mas’ul xodim')),
                ('city', models.ForeignKey(blank=True, help_text='Ixtiyoriy.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicants_city', to='locations.city', verbose_name='Shahar (mijoz)')),
                ('country', models.ForeignKey(blank=True, help_text='Mijoz istiqomat qiladigan mamlakat (ixtiyoriy).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicants_country', to='locations.country', verbose_name='Mamlakat (mijoz)')),
                ('tour', models.ForeignKey(blank=True, help_text='Agar mijoz aniq tur tanlagan bo‘lsa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='tours.tour', verbose_name='Tanlangan tur')),
            ],
            options={
                'verbose_name': 'Tur arizasi',
                'verbose_name_plural': 'Tur arizalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('file', models.FileField(upload_to='leads/attachments/', verbose_name='Fayl')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Nomi')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='leads.application', verbose_name='Ariza')),
            ],
            options={
                'verbose_name': 'Biriktirilgan fayl',
                'verbose_name_plural': 'Biriktirilgan fayllar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('full_name', models.CharField(max_length=120, verbose_name='To‘liq ism')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator('^\\+?[0-9\\-\\s\\(\\)]{6,}$')], verbose_name='Telefon')),
                ('subject', models.CharField(choices=[('general', 'Umumiy savol'), ('booking', 'Bron / Band qilish'), ('support', 'Qo‘llab-quvvatlash'), ('partnership', 'Hamkorlik'), ('other', 'Boshqa')], default='general', max_length=20, verbose_name='Mavzu')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('read', 'O‘qildi'), ('answered', 'Javob berildi'), ('spam', 'Spam')], default='new', max_length=16, verbose_name='Holat')),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Mijoz IP')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='User-Agent')),
                ('referrer', models.CharField(blank=True, max_length=500, verbose_name='Referrer URL')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_messages', to=settings.AUTH_USER_MODEL, verbose_name='Mas’ul xodim')),
            ],
            options={
                'verbose_name': 'Kontakt xabar',
                'verbose_name_plural': 'Kontakt xabarlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
