# Generated by Django 5.2.7 on 2025-10-24 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_itineraryday_description_en_and_more'),
    ]

    operations = [
    ]
