# Generated by Django 5.2.7 on 2025-10-24 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_merge_tag_name_translations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourtag',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='tourtag',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='tourtag',
            name='name_uz',
        ),
    ]
