# Generated by Django 5.2.7 on 2025-10-22 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('iso2', models.CharField(max_length=2, unique=True)),
                ('iso3', models.CharField(blank=True, max_length=3, unique=True)),
                ('m49', models.PositiveIntegerField(blank=True, null=True)),
                ('numeric', models.PositiveIntegerField(blank=True, null=True)),
                ('phone_code', models.CharField(blank=True, max_length=8)),
                ('region', models.CharField(blank=True, max_length=64)),
                ('subregion', models.CharField(blank=True, max_length=64)),
                ('capital', models.CharField(blank=True, max_length=128)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('tz_primary', models.CharField(blank=True, max_length=64)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('ascii_name', models.CharField(blank=True, max_length=150)),
                ('admin1', models.CharField(blank=True, max_length=150)),
                ('admin2', models.CharField(blank=True, max_length=150)),
                ('tz', models.CharField(blank=True, max_length=64)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('geoname_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='locations.country')),
            ],
            options={
                'ordering': ['-population', 'name'],
                'indexes': [models.Index(fields=['name'], name='locations_c_name_5719ba_idx'), models.Index(fields=['country', 'name'], name='locations_c_country_a5360f_idx'), models.Index(fields=['-population'], name='locations_c_populat_007e56_idx')],
            },
        ),
    ]
