# Generated by Django 5.2.7 on 2025-10-22 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('singleton_key', models.CharField(default='about', max_length=32, unique=True, verbose_name='Yagona kalit')),
                ('hero_title', models.CharField(blank=True, max_length=200, verbose_name='Sarlavha')),
                ('hero_subtitle', models.CharField(blank=True, max_length=300, verbose_name='Qisqa tavsif')),
                ('hero_image', models.ImageField(blank=True, upload_to='pages/about/', verbose_name='Fon rasm')),
                ('video_url', models.URLField(blank=True, max_length=500, verbose_name='Video havola')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Meta sarlavha')),
                ('meta_description', models.CharField(blank=True, max_length=255, verbose_name='Meta tavsif')),
            ],
            options={
                'verbose_name': 'Biz haqimizda (sahifa)',
                'verbose_name_plural': 'Biz haqimizda (sahifa)',
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('singleton_key', models.CharField(default='contact', max_length=32, unique=True, verbose_name='Yagona kalit')),
                ('hero_title', models.CharField(blank=True, max_length=200, verbose_name='Sarlavha')),
                ('hero_subtitle', models.CharField(blank=True, max_length=300, verbose_name='Qisqa tavsif')),
                ('intro_html', models.TextField(blank=True, verbose_name='Kirish matni (HTML)')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Meta sarlavha')),
                ('meta_description', models.CharField(blank=True, max_length=255, verbose_name='Meta tavsif')),
            ],
            options={
                'verbose_name': 'Aloqa (sahifa)',
                'verbose_name_plural': 'Aloqa (sahifa)',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('singleton_key', models.CharField(default='default', help_text="Ushbu yozuvni unikallash uchun xizmat qiladi (odatda 'default').", max_length=32, unique=True, verbose_name='Yagona kalit')),
                ('org_name', models.CharField(blank=True, help_text='Masalan: Horun Travel', max_length=200, verbose_name='Tashkilot nomi')),
                ('slogan', models.CharField(blank=True, help_text='Qisqa shior (ixtiyoriy).', max_length=200, verbose_name='Slogan')),
                ('logo', models.ImageField(blank=True, upload_to='site/logo/', verbose_name='Logo (yorug‘ mavzu)')),
                ('logo_dark', models.ImageField(blank=True, upload_to='site/logo/', verbose_name='Logo (qorong‘i mavzu)')),
                ('favicon', models.ImageField(blank=True, upload_to='site/favicon/', verbose_name='Favicon')),
                ('primary_phone', models.CharField(blank=True, help_text='Masalan: +998 90 123 45 67', max_length=32, verbose_name='Asosiy telefon')),
                ('primary_email', models.EmailField(blank=True, help_text='Masalan: info@namuna.uz', max_length=254, verbose_name='Asosiy email')),
                ('meta_title', models.CharField(blank=True, help_text='SEO uchun sarlavha (asosiy sahifa).', max_length=255, verbose_name='Meta sarlavha')),
                ('meta_description', models.CharField(blank=True, help_text='SEO uchun qisqa tavsif (asosiy sahifa).', max_length=255, verbose_name='Meta tavsif')),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Bo‘lim sarlavhasi')),
                ('body', models.TextField(blank=True, help_text='HTML yoki Markdown matn (ixtiyoriy).', verbose_name='Bo‘lim matni')),
                ('image', models.ImageField(blank=True, upload_to='pages/about/sections/', verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Tartib')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='siteinfo.aboutpage', verbose_name='Sahifa')),
            ],
            options={
                'verbose_name': 'Bo‘lim',
                'verbose_name_plural': 'Bo‘limlar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(blank=True, help_text='Masalan: Bosh ofis, Samarqand filiali va h.k.', max_length=120, verbose_name='Joy nomi')),
                ('address_line', models.CharField(blank=True, max_length=255, verbose_name='Manzil')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Pochta indeksi')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Kenglik (lat)')),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Uzunlik (lng)')),
                ('map_embed_url', models.URLField(blank=True, help_text='Google Maps embed havolasi (ixtiyoriy).', max_length=800, verbose_name='Xarita (embed URL)')),
                ('place_id', models.CharField(blank=True, max_length=128, verbose_name='Place ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Tartib')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Asosiy manzil')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='org_locations', to='locations.city', verbose_name='Shahar')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org_locations', to='locations.country', verbose_name='Davlat')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='siteinfo.sitesettings', verbose_name='Sayt sozlamalari')),
            ],
            options={
                'verbose_name': 'Manzil',
                'verbose_name_plural': 'Manzillar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('type', models.CharField(choices=[('phone', 'Telefon'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('website', 'Veb-sayt'), ('fax', 'Faks'), ('other', 'Boshqa')], default='phone', max_length=16, verbose_name='Kanal turi')),
                ('label', models.CharField(blank=True, help_text='Masalan: Call center, Sotuv, Booking va h.k.', max_length=64, verbose_name='Yorliq')),
                ('value', models.CharField(help_text='Telefon: +998..., Email: example@..., Telegram: https://t.me/... va h.k.', max_length=256, verbose_name='Qiymat')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Tartib')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Asosiy kanal')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='siteinfo.sitesettings', verbose_name='Sayt sozlamalari')),
            ],
            options={
                'verbose_name': 'Aloqa kanali',
                'verbose_name_plural': 'Aloqa kanallari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('provider', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('telegram', 'Telegram'), ('twitter', 'X / Twitter'), ('linkedin', 'LinkedIn'), ('vk', 'VK'), ('other', 'Boshqa')], default='instagram', max_length=20, verbose_name='Platforma')),
                ('label', models.CharField(blank=True, help_text='Masalan: @username yoki qisqa izoh (ixtiyoriy).', max_length=64, verbose_name='Yorliq')),
                ('url', models.URLField(max_length=500, verbose_name='Havola')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Tartib')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='siteinfo.sitesettings', verbose_name='Sayt sozlamalari')),
            ],
            options={
                'verbose_name': 'Ijtimoiy tarmoq',
                'verbose_name_plural': 'Ijtimoiy tarmoqlar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Dushanba'), (1, 'Seshanba'), (2, 'Chorshanba'), (3, 'Payshanba'), (4, 'Juma'), (5, 'Shanba'), (6, 'Yakshanba')], verbose_name='Hafta kuni')),
                ('closed', models.BooleanField(default=False, help_text='Ushbu kunda ishlanmaydi.', verbose_name='Yopiq')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='Ochiladi')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='Yopiladi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='siteinfo.location', verbose_name='Manzil')),
            ],
            options={
                'verbose_name': 'Ish vaqti',
                'verbose_name_plural': 'Ish vaqtlari',
                'ordering': ['order', 'weekday', 'id'],
                'unique_together': {('location', 'weekday')},
            },
        ),
    ]
