# Generated by Django 5.2.7 on 2025-10-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='hero_subtitle_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_subtitle_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_subtitle_uz',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_title_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta tavsif'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='meta_description_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta tavsif'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='meta_description_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta tavsif'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta sarlavha'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta sarlavha'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='meta_title_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta sarlavha'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='body_en',
            field=models.TextField(blank=True, help_text='HTML yoki Markdown matn (ixtiyoriy).', null=True, verbose_name='Bo‘lim matni'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='body_ru',
            field=models.TextField(blank=True, help_text='HTML yoki Markdown matn (ixtiyoriy).', null=True, verbose_name='Bo‘lim matni'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='body_uz',
            field=models.TextField(blank=True, help_text='HTML yoki Markdown matn (ixtiyoriy).', null=True, verbose_name='Bo‘lim matni'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bo‘lim sarlavhasi'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bo‘lim sarlavhasi'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='title_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bo‘lim sarlavhasi'),
        ),
        migrations.AddField(
            model_name='contactchannel',
            name='label_en',
            field=models.CharField(blank=True, help_text='Masalan: Call center, Sotuv, Booking va h.k.', max_length=64, null=True, verbose_name='Yorliq'),
        ),
        migrations.AddField(
            model_name='contactchannel',
            name='label_ru',
            field=models.CharField(blank=True, help_text='Masalan: Call center, Sotuv, Booking va h.k.', max_length=64, null=True, verbose_name='Yorliq'),
        ),
        migrations.AddField(
            model_name='contactchannel',
            name='label_uz',
            field=models.CharField(blank=True, help_text='Masalan: Call center, Sotuv, Booking va h.k.', max_length=64, null=True, verbose_name='Yorliq'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='hero_subtitle_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='hero_subtitle_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='hero_subtitle_uz',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='hero_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='hero_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='hero_title_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='intro_html_en',
            field=models.TextField(blank=True, null=True, verbose_name='Kirish matni (HTML)'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='intro_html_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Kirish matni (HTML)'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='intro_html_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Kirish matni (HTML)'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta tavsif'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='meta_description_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta tavsif'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='meta_description_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta tavsif'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta sarlavha'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta sarlavha'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='meta_title_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta sarlavha'),
        ),
        migrations.AddField(
            model_name='location',
            name='address_line_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='location',
            name='address_line_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='location',
            name='address_line_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='location',
            name='name_en',
            field=models.CharField(blank=True, help_text='Masalan: Bosh ofis, Samarqand filiali va h.k.', max_length=120, null=True, verbose_name='Joy nomi'),
        ),
        migrations.AddField(
            model_name='location',
            name='name_ru',
            field=models.CharField(blank=True, help_text='Masalan: Bosh ofis, Samarqand filiali va h.k.', max_length=120, null=True, verbose_name='Joy nomi'),
        ),
        migrations.AddField(
            model_name='location',
            name='name_uz',
            field=models.CharField(blank=True, help_text='Masalan: Bosh ofis, Samarqand filiali va h.k.', max_length=120, null=True, verbose_name='Joy nomi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description_en',
            field=models.CharField(blank=True, help_text='SEO uchun qisqa tavsif (asosiy sahifa).', max_length=255, null=True, verbose_name='Meta tavsif'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description_ru',
            field=models.CharField(blank=True, help_text='SEO uchun qisqa tavsif (asosiy sahifa).', max_length=255, null=True, verbose_name='Meta tavsif'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description_uz',
            field=models.CharField(blank=True, help_text='SEO uchun qisqa tavsif (asosiy sahifa).', max_length=255, null=True, verbose_name='Meta tavsif'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_title_en',
            field=models.CharField(blank=True, help_text='SEO uchun sarlavha (asosiy sahifa).', max_length=255, null=True, verbose_name='Meta sarlavha'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_title_ru',
            field=models.CharField(blank=True, help_text='SEO uchun sarlavha (asosiy sahifa).', max_length=255, null=True, verbose_name='Meta sarlavha'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_title_uz',
            field=models.CharField(blank=True, help_text='SEO uchun sarlavha (asosiy sahifa).', max_length=255, null=True, verbose_name='Meta sarlavha'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='org_name_en',
            field=models.CharField(blank=True, help_text='Masalan: Horun Travel', max_length=200, null=True, verbose_name='Tashkilot nomi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='org_name_ru',
            field=models.CharField(blank=True, help_text='Masalan: Horun Travel', max_length=200, null=True, verbose_name='Tashkilot nomi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='org_name_uz',
            field=models.CharField(blank=True, help_text='Masalan: Horun Travel', max_length=200, null=True, verbose_name='Tashkilot nomi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='slogan_en',
            field=models.CharField(blank=True, help_text='Qisqa shior (ixtiyoriy).', max_length=200, null=True, verbose_name='Slogan'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='slogan_ru',
            field=models.CharField(blank=True, help_text='Qisqa shior (ixtiyoriy).', max_length=200, null=True, verbose_name='Slogan'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='slogan_uz',
            field=models.CharField(blank=True, help_text='Qisqa shior (ixtiyoriy).', max_length=200, null=True, verbose_name='Slogan'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='label_en',
            field=models.CharField(blank=True, help_text='Masalan: @username yoki qisqa izoh (ixtiyoriy).', max_length=64, null=True, verbose_name='Yorliq'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='label_ru',
            field=models.CharField(blank=True, help_text='Masalan: @username yoki qisqa izoh (ixtiyoriy).', max_length=64, null=True, verbose_name='Yorliq'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='label_uz',
            field=models.CharField(blank=True, help_text='Masalan: @username yoki qisqa izoh (ixtiyoriy).', max_length=64, null=True, verbose_name='Yorliq'),
        ),
    ]
